name: tests-check

on: push

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2 
    run: make lint
    run: make test
    